### PR TITLE
Add nix files

### PR DESCRIPTION
**Pull request by tfc**
This PR does...

- pack the stack LTS packages used by this project into the file `stackage-13.10.nix`
- add a `default.nix` to enable `nix-shell` and `nix-build` workflows
- downgrade from LTS 13.11 to 13.10, because for weird reasons `stack2nix` (and apparently `stack`) wants to use GHC 8.6.4, although https://www.stackage.org/lts-13.11 officially uses 8.6.3 - nix currently has no package for that yet.

### CODE REVIEW

**Comment by blitz** [comment]
If you generated this via a script, can you drop this in `scripts/`? I've changed the dependencies since you wrote this and it would be a pain to manually sync.

**Comment by tfc** [comment]
makes sense, will do

**Comment by tfc** [comment]
@blitz done

**Comment by blitz** [comment]
Any ideas what's going on here?

```
% nix-build --show-trace
error: while evaluating anonymous function at /home/julian/src/own/obiwan/default.nix:1:1, called from undefined position:
while evaluating 'id' at /nix/store/jpgfbiaa9ix2as76gxfa7gazjd2s1spp-nixpkgs-18.09pre132003.13e74a838db/nixpkgs/lib/trivial.nix:9:8, called from /home/julian/src/own/obiwan/default.nix:10:9:
while evaluating anonymous function at /home/julian/src/own/obiwan/nix/stackage.nix:3:1, called from /home/julian/src/own/obiwan/default.nix:8:14:
while evaluating the attribute 'haskell.packages.ghc863' at /nix/store/jpgfbiaa9ix2as76gxfa7gazjd2s1spp-nixpkgs-18.09pre132003.13e74a838db/nixpkgs/pkgs/top-level/haskell-packages.nix:106:3:
attribute 'ghc863' missing, at /home/julian/src/own/obiwan/nix/stackage.nix:4:14

% ./scripts/update_nix.sh
[...]
Ensuring cabal2nix version is >= 2.2.1 ...
Ensuring git version is >= 2 ...
Ensuring cabal version is >= 1 ...
stack2nix: Failed to parse ./stack.yaml
CallStack (from HasCallStack):
  error, called at src/Stack2nix.hs:158:24 in stack2nix-0.1.3.0-6DrVsHUo3YdGNMg7jBN0R7:Stack2nix
```

**Comment by tfc** [comment]
Your `nixpkgs` is on this commit https://github.com/NixOS/nixpkgs/commit/13e74a838db, which is roughly a year old.

Typical solution: `nix-channel --update` (assuming `nix-channel --list` shows a sane channel)
Another possible solution: I could also add a pinned fresh `nixpkgs` channel to this repo, so everyone who builds this would work with the *exact* same commits of everything in the toolchain.

I suggest you update your nix channel and try again then it works. And at some point it may make sense to pin the nixpkgs, but generally i see more sense in this for very large projects with a lot of moving parts.

**Comment by tfc** [comment]
Realized that it's possible to get rid of `cabal2nix` altogether, pushed that change.

**Comment by blitz** [comment]
I've updated my nix channel thingy. When I try to recreate `stackage.nix`, I get:

```
% ./update_stackage.sh
[...]
 + cabal2nix --subpath . --system x86_64-linux --compiler ghc-8.6.3 cabal://zip-stream-0.2.0.1
+ cabal2nix --subpath . --system x86_64-linux --compiler ghc-8.6.3 cabal://zlib-0.6.2
+ cabal2nix --subpath . --system x86_64-linux --compiler ghc-8.6.3 cabal://zippers-0.2.5
+ cabal2nix --subpath . --system x86_64-linux --compiler ghc-8.6.3 cabal://zlib-lens-0.1.2.1
+ cabal2nix --subpath . --system x86_64-linux --compiler ghc-8.6.3 cabal://zlib-bindings-0.1.1.5
+ cabal2nix --subpath . --system x86_64-linux --compiler ghc-8.6.3 cabal://zot-0.0.3
+ cabal2nix --subpath . --system x86_64-linux --compiler ghc-8.6.3 cabal://zstd-0.1.0.0
+ cabal2nix --subpath . --system x86_64-linux --compiler ghc-8.6.3 cabal://ztail-1.2.0.2
stack2nix: <stdout>: commitBuffer: invalid argument (invalid character)
```

**Comment by tfc** [comment]
ok, on what nixpkgs commit are you now?

**Comment by blitz** [comment]
I'm on https://nixos.org/channels/nixpkgs-unstable as of now.

**Comment by blitz** [comment]
I'm also thinking about how to avoid dumping the very large and often updated and completely boring `stackage.nix` into the repo. What about building this as part of the CI and including it in release tarballs? Travis seems to be able to do that.

That would mean that normal development would still happen with stack (and all its conveniences) and people can consume releases via Nix.

**Comment by tfc** [comment]
hm i don't use stack any longer at all. I like stack*age* for its combination of always-working library versions. And then it makes a lot of sense to have a stackage file. Doesn't hurt.

**Comment by blitz** [comment]
Using stack is the way of least resistance for people to join development. It's what all the Haskell docs/tutorials assume. It also spares me manually fiddling with my very comfortable Haskell dev setup in Spacemacs. ;) Having the stackage file built automatically as part of a release build would also mean its always up-to-date.

**Comment by tfc** [comment]
That are indeed 2 completely separate discussions. Nothing that i ever suggested would keep anyone from continuing to use stack as-is.

**Comment by blitz** [comment]
> That are indeed 2 completely separate discussions.

True. :)

> Nothing that i ever suggested would keep anyone from continuing to use stack as-is.

I'm trying to avoid carrying files in the repo that can go out of sync and complicating my dev setup. There should be One Source of Truth™.

**Comment by tfc** [comment]
That is understandable and i see that this is going towards a little culture clash of the tools and technical requirements of everything. Allow me discuss this with a longer post as i am thankful that you show general opennness to nix technology:

The nix idea is: You start nix on your repository and it is possible to build everything from a (maybe pinned version of) `<nixpkgs>` and your repo. Everything else can be downloaded from source from one of the *allowed* sources (e.g. github) and only by the `nix` process (everything else runs in offline namespaces). This results in great purity of everything and even with pinned nixpkgs this will be able to build forever, even with bit-identity across build machines (although it's often the compiler of a language that doesn't support that).

As soon as we say "we don't want the stackage file to be saved in this repo", we are forced to run `stack` or `stack2nix`. In the first case, `stack` would simply be the tool that is executed by nix as the standard builder. This is a completely feasible thing to do - with the unpleasant detail that all the build dependencies are managed by stack and not nix, while nix shows such elegant ways to do so systemwide - plus nix can download compiled libraries from the nix cache, thus being faster than stack which has no such thing. The second possibility means that we would build a derivation that outputs the stackage.nix file in the nix store and then uses that for building, so we have 2 derivations to process for the final build product.

The disadvantages of the second way are for nix users:

1.) This split-derivation workflow for dependency definition is less comfortable than just having the stackage file there (while understanding and liking the one-source-of-truth thinking myself, i see dependencies rarely changing and at the same time it's like **really** simple to fix the stackage file. In any CI where nix is used for building, it would also **immediately** become obvious that someone forgot to update it before code is merged)
2.) It is not compatible with the `sandbox = true` setting in nix, which became default half a year ago. Whole linux systems with exotic build configurations, cross compiling to windows, to mac, to ARM, etc. etc. are possible with nix with sandboxing enabled (and it's wonderful to see this working - no other dependency management on the world is this pure) - but not with this repo if we force users to use `stack2nix` or `stack` which try to download stuff themselves from possibly impure sources.

There are a lot of package managers for python, npm, ruby, etc. etc.... and nix tools exist for those that enable the developer to create packagelist.nix files that can be committed into the repository, in order to ultimatively enable to build software without the use of a single impure tool (Such tools are impure by using network connections to unknown servers that fetch data that is not nicely deterministic by design - as the checkout of a git commit by its commit ID).

*My* summary of this long monologue-discussion is: By not committing the stackage file you are sticking to "One source of definitions" but not really "one source of truth", because you force the user to consult the stackage servers as another source of truth by tools other than git (which is pure and deterministic by design). For the price of a potentally large stackage file being committed into this repo, you give the user a **full** and tested list of dependencies of this project that can be checked out using just pure and deterministic tools. Just by offline comparing against a committed list of commit hashes of _all_ the dependency libraries, you can say if you have everything cached for a perfectly deterministic build, or not, which is a powerful and nicely independent position.

[while at the same time not hindering anyone to still use stack without ever having heard of nix]

**Pull request closed without merging**
